### ISSUE TITLE
How fix this error?

### ISSUE THREAD

**Issue by mokhtarabadi** [enarjord/passivbot#113]
```
Traceback (most recent call last):
  File "~passivbot/venv/lib/python3.8/site-packages/redis/connection.py", line 706, in send_packed_command
    sendall(self._sock, item)
  File "~passivbot/venv/lib/python3.8/site-packages/redis/_compat.py", line 9, in sendall
    return sock.sendall(*args, **kwargs)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "optimize.py", line 246, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "optimize.py", line 240, in main
    analysis = backtest_tune(ticks, config)
  File "optimize.py", line 174, in backtest_tune
    analysis = tune.run(
  File "~passivbot/venv/lib/python3.8/site-packages/ray/tune/tune.py", line 306, in run
    experiments[i] = Experiment(
  File "~passivbot/venv/lib/python3.8/site-packages/ray/tune/experiment.py", line 149, in __init__
    self._run_identifier = Experiment.register_if_needed(run)
  File "~passivbot/venv/lib/python3.8/site-packages/ray/tune/experiment.py", line 294, in register_if_needed
    register_trainable(name, run_object)
  File "~passivbot/venv/lib/python3.8/site-packages/ray/tune/registry.py", line 71, in register_trainable
    _global_registry.register(TRAINABLE_CLASS, name, trainable)
  File "~passivbot/venv/lib/python3.8/site-packages/ray/tune/registry.py", line 124, in register
    self.flush_values()
  File "~passivbot/venv/lib/python3.8/site-packages/ray/tune/registry.py", line 146, in flush_values
    _internal_kv_put(_make_key(category, key), value, overwrite=True)
  File "~passivbot/venv/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "~passivbot/venv/lib/python3.8/site-packages/ray/experimental/internal_kv.py", line 35, in _internal_kv_put
    updated = worker.redis_client.hset(key, "value", value)
  File "~passivbot/venv/lib/python3.8/site-packages/redis/client.py", line 3050, in hset
    return self.execute_command('HSET', name, *items)
  File "~passivbot/venv/lib/python3.8/site-packages/redis/client.py", line 900, in execute_command
    conn.send_command(*args)
  File "~passivbot/venv/lib/python3.8/site-packages/redis/connection.py", line 725, in send_command
    self.send_packed_command(self.pack_command(*args),
  File "~passivbot/venv/lib/python3.8/site-packages/redis/connection.py", line 717, in send_packed_command
    raise ConnectionError("Error %s while writing to socket. %s." %
redis.exceptions.ConnectionError: Error 32 while writing to socket. Broken pipe.
```

**Comment by enarjord** [comment]
optimizer won't work if VPN is enabled

try downloading needed historical trade data first, then turn off VPN and run optimizer

**Comment by mokhtarabadi** [comment]
I download the data, but I see this error even when I turned off my VPN
I fixed it by resetting the configs to default values, I think there is a problem with Redis max memory usage
it is possible to use GPU for optimize!? (I don't have enough information about that just ask a question)

**Comment by enarjord** [comment]
i believe GPUs need very simple instructions, which are run in parallel across hundreds of gpu cores.  so backtester is too complex for GPU parallelization, according to my understanding

**Comment by mokhtarabadi** [comment]
Fix problem by turning off the wfo option in optimize config

Close that if need
