### ISSUE TITLE
report issue =)

### ISSUE THREAD

**Issue by pavelxx1** [enarjord/passivbot#130]
`ching ticks... 256258 of 256618
debug len ticks, prices deque, ema_span
257303 256618 256618
The lock file has been removed succesfully
Task exception was never retrieved
future: <Task finished name='Task-317' coro=<Bot.decide() done, defined at c:\Users\Zver\PycharmProjects\passivbot\passivbot.py:417> exception=KeyError('long')>
Traceback (most recent call last):
  File "c:\Users\Zver\PycharmProjects\passivbot\passivbot.py", line 438, in decide
    await self.update_output_information()
  File "c:\Users\Zver\PycharmProjects\passivbot\passivbot.py", line 443, in update_output_information
    line += f"l {self.position['long']['size']} @ "
KeyError: 'long'
Task exception was never retrieved
future: <Task finished name='Task-318' coro=<Bot.decide() done, defined at c:\Users\Zver\PycharmProjects\passivbot\passivbot.py:417> exception=KeyError('long')>
Traceback (most recent call last):
  File "c:\Users\Zver\PycharmProjects\passivbot\passivbot.py", line 438, in decide
    await self.update_output_information()
  File "c:\Users\Zver\PycharmProjects\passivbot\passivbot.py", line 443, in update_output_information
    line += f"l {self.position['long']['size']} @ "
KeyError: 'long'
Task exception was never retrieved
future: <Task finished name='Task-321' coro=<Bot.decide() done, defined at c:\Users\Zver\PycharmProjects\passivbot\passivbot.py:417> exception=KeyError('long')>
Traceback (most recent call last):
  File "c:\Users\Zver\PycharmProjects\passivbot\passivbot.py", line 438, in decide
    await self.update_output_information()
  File "c:\Users\Zver\PycharmProjects\passivbot\passivbot.py", line 443, in update_output_information
    line += f"l {self.position['long']['size']} @ "
KeyError: 'long'`

**Comment by enarjord** [comment]
might be the windows clock isn't synced with binance server's clock
