### ISSUE TITLE
File "optimize.py", line 265, in <module>     asyncio.run(main())

### ISSUE THREAD

**Issue by ghostnetrn** [enarjord/passivbot#140]
2021-06-08T01:07:13  Fetching ETHUSDT 2021-06-06 
Traceback (most recent call last):
  File "optimize.py", line 265, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "optimize.py", line 243, in main
    ticks = await downloader.get_ticks(True)
  File "/root/binance/downloader.py", line 621, in get_ticks
    await self.download_ticks()
  File "/root/binance/downloader.py", line 466, in download_ticks
    end_id = sys.maxsize if end_id == 0 else end_id - 1
NameError: name 'sys' is not defined
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fef7a722640>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fef7a6cbfa0>, 11219.746704129)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fef7a7229d0>

**Comment by pavelxx1** [comment]
add
 `import sys`
in downloader.py

**Comment by ghostnetrn** [comment]
Perfect. Thanks!
