### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by eazylook** [enarjord/passivbot#22]
Starting binance example_user
2021-02-19T09:51:47  settings for user example_user not found, using default settings

loaded settings:
{'balance_pct': 1.0,
 'config_name': 'XRPUSDT',
 'cross_mode': True,
 'ddown_factor': 0.79,
 'entry_qty_pct': 0.00368,
 'grid_coefficient': 277.48,
 'grid_spacing': 0.00187,
 'indicator_settings': {'do_long': True,
                        'do_shrt': True,
                        'funding_fee_collect_mode': False,
                        'ohlcv_rsi': {'n_periods': 21, 'period_ms': 1800000},
                        'tick_ema': {'span': 59854.0}},
 'leverage': 30.0,
 'logging_level': 0,
 'market_stop_loss': False,
 'max_markup': 0.02161,
 'min_close_qty_multiplier': 0.24,
 'min_markup': 0.00137,
 'n_close_orders': 13.0,
 'n_entry_orders': 8,
 'stop_loss_liq_diff': 0.0912,
 'stop_loss_pos_price_diff': 0.1193,
 'stop_loss_pos_reduction': 0.092,
 'symbol': 'DASHUSDT'}
Traceback (most recent call last):
  File "C:\Users\qwerty\Desktop\ddd\binance.py", line 367, in <module>
    asyncio.run(main())
  File "C:\Users\qwerty\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\qwerty\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\qwerty\Desktop\ddd\binance.py", line 362, in main
    bot = await create_bot(sys.argv[1], load_settings('binance', sys.argv[1]))
  File "C:\Users\qwerty\Desktop\ddd\binance.py", line 117, in create_bot
    await bot._init()
  File "C:\Users\qwerty\Desktop\ddd\binance.py", line 132, in _init
    exchange_info, leverage_bracket = await asyncio.gather(
  File "C:\Users\qwerty\Desktop\ddd\venv\lib\site-packages\ccxt\async_support\binance.py", line 2565, in request
    response = await self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\qwerty\Desktop\ddd\venv\lib\site-packages\ccxt\async_support\base\exchange.py", line 94, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "C:\Users\qwerty\Desktop\ddd\venv\lib\site-packages\ccxt\async_support\binance.py", line 2495, in sign
    signature = self.hmac(self.encode(query), self.encode(self.secret))
  File "C:\Users\qwerty\Desktop\ddd\venv\lib\site-packages\ccxt\base\exchange.py", line 1233, in encode
    return string.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 64-66: ordinal not in range(256)
binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a pla
ce when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000031D3BFD820>
bot stopped, attempting restart in 27 seconds

**Comment by JohnKearney1** [comment]
I'm unable to replicate, make sure your CCXT package is up to date, some older versions are incompatible. Will keep looking.
'pip3 install ccxt'
