### ISSUE TITLE
I want to backtest it back, but I keep getting this error. what should I do.

### ISSUE THREAD

**Issue by furkanbey01** [enarjord/passivbot#291]
```
a@ubuntu:~/Desktop/passivbot$ python3 backtest.py path/to/multi_122_symbols.json

using numba
fetching market_specific_settings...

failed to fetch market_specific_settings cannot import name 'KeyboardButton' from 'telegram' (/home/a/.local/lib/python3.8/site-packages/telegram/__init__.py) 

using cached market_specific_settings
Traceback (most recent call last):
  File "backtest.py", line 73, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "backtest.py", line 54, in main
    config = await prepare_backtest_config(args)
  File "/home/a/Desktop/passivbot/procedures.py", line 77, in prepare_backtest_config
    await add_market_specific_settings(config)
  File "/home/a/Desktop/passivbot/procedures.py", line 106, in add_market_specific_settings
    config.update(market_specific_settings)

UnboundLocalError: local variable 'market_specific_settings' referenced before assignment
```

**Comment by TheRealSwayMoney** [comment]
Did you ever figure it out?

**Comment by topdollar3** [comment]
In case anyone got this error, check your symbol syntax for exemple ADAUSDT and not ADA/USDT
