### ISSUE TITLE
please take a look is it SOLUSDT ticker problem or others? 

### ISSUE THREAD

**Issue by mdnaimul22** [enarjord/passivbot#304]
linear perpetual
2021-12-15T12:49:23  Validating file 122100000_122199999_1631285379463_1631287254700.csv 2021-09-10T20:49:39.463000 
Traceback (most recent call last):
  File "optimize.py", line 361, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "optimize.py", line 357, in main
    await execute_optimize(config)
  File "optimize.py", line 322, in execute_optimize
    data = await downloader.get_sampled_ticks()
  File "/home/boss/passiv510/downloader.py", line 685, in get_sampled_ticks
    await self.download_ticks()
  File "/home/boss/passiv510/downloader.py", line 376, in download_ticks
    missing, df, gaps = self.validate_dataframe(df)
  File "/home/boss/passiv510/downloader.py", line 81, in validate_dataframe
    if missing_ids := df["trade_id"].iloc[0] % 100000 != 0:
  File "/home/boss/passiv510/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/boss/passiv510/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1566, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/boss/passiv510/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1500, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fcc25d965b0>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fcc2abe5b20>, 4176.991005211), (<aiohttp.client_proto.ResponseHandler object at 0x7fcc25d335e0>, 4177.099195716)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fcc25d96130>

**Comment by mdnaimul22** [comment]
i am fetching this aiohttp issue only with sol others tick are ok.
