### ISSUE TITLE
Bybit live is broken

### ISSUE THREAD

**Issue by riodda** [enarjord/passivbot#313]
Tryed to start a live bot on Bybit but the bot returns several errors:

```
dario@passivbot:~/passivbot$ python3 /home/dario/passivbot/passivbot.py bybit_01 SOLUSDT configs/live/test_1.json 
not using numba
linear perpetual
error with update position 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/dario/passivbot/passivbot.py", line 135, in update_position
    position = await self.fetch_position()
  File "/home/dario/passivbot/bybit.py", line 177, in fetch_position
    long_pos = [e for e in fetched['result'] if e['side'] == 'Buy'][0]
TypeError: 'NoneType' object is not iterable
using config
{'assigned_balance': None,
 'c_mult': 1.0,
 'config_name': 'allround_long&short_216days_122symbols_2.84%longPAdist_2.51%shortPAdist',
 'cross_wallet_pct': 1.0,
 'do_long': True,
 'do_shrt': True,
 'exchange': 'bybit',
 'hedge_mode': True,
 'inverse': False,
 'last_price_diff_limit': 0.3,
 'live_config_path': 'configs/live/test_1.json',
 'logging_level': 0,
 'long': {'enabled': True,
          'eprice_exp_base': 1.083520871230325,
          'eprice_pprice_diff': 0.01641816059809555,
          'grid_span': 0.3057251433362501,
          'initial_qty_pct': 0.0066671170998285545,
          'markup_range': 0.0188609452872319,
          'max_n_entry_orders': 10,
          'min_markup': 0.01857069739027485,
          'n_close_orders': 6,
          'pbr_limit': 1.0,
          'secondary_pbr_allocation': 0.31459646386673007,
          'secondary_pprice_diff': 0.3902061274077424},
 'long_mode': None,
 'market_type': 'futures',
 'max_leverage': 25,
 'min_cost': 0.0,
 'min_qty': 0.1,
 'price_step': 0.005,
 'profit_trans_pct': 0.0,
 'qty_step': 0.1,
 'shrt': {'enabled': True,
          'eprice_exp_base': 1.1704211490094925,
          'eprice_pprice_diff': 0.018053689141866988,
          'grid_span': 0.4072413740914343,
          'initial_qty_pct': 0.0016275180323573374,
          'markup_range': 0.0024591824834022838,
          'max_n_entry_orders': 11,
          'min_markup': 0.002,
          'n_close_orders': 7,
          'pbr_limit': 1.0,
          'secondary_pbr_allocation': 0.5001046919136795,
          'secondary_pprice_diff': 0.0940389806688959},
 'shrt_mode': None,
 'symbol': 'SOLUSDT',
 'user': 'bybit_01'}
error with update open orders 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/dario/passivbot/passivbot.py", line 106, in update_open_orders
    open_orders = await self.fetch_open_orders()
  File "/home/dario/passivbot/bybit.py", line 134, in fetch_open_orders
    return [{'order_id': elm['order_id'],
TypeError: 'NoneType' object is not iterable
error with update position 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/dario/passivbot/passivbot.py", line 135, in update_position
    position = await self.fetch_position()
  File "/home/dario/passivbot/bybit.py", line 177, in fetch_position
    long_pos = [e for e in fetched['result'] if e['side'] == 'Buy'][0]
TypeError: 'NoneType' object is not iterable
{'ret_code': 10004, 'ret_msg': 'error sign! origin_string[api_key=&buy_leverage=7&is_isolated=false&sell_leverage=7&symbol=SOLUSDT&timestamp=1641205855338]', 'ext_code': '', 'ext_info': '', 'result': None, 'time_now': '1641205855.381739'}
{'ret_code': 10004, 'ret_msg': 'error sign! origin_string[api_key=&buy_leverage=7&sell_leverage=7&symbol=SOLUSDT&timestamp=1641205855522]', 'ext_code': '', 'ext_info': '', 'result': None, 'time_now': '1641205855.564872'}
2022-01-03T10:30:55  url wss://stream.bybit.com/realtime_private 
error with update open orders 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/dario/passivbot/passivbot.py", line 106, in update_open_orders
    open_orders = await self.fetch_open_orders()
  File "/home/dario/passivbot/bybit.py", line 134, in fetch_open_orders
    return [{'order_id': elm['order_id'],
TypeError: 'NoneType' object is not iterable
error with update position 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/dario/passivbot/passivbot.py", line 135, in update_position
    position = await self.fetch_position()
  File "/home/dario/passivbot/bybit.py", line 177, in fetch_position
    long_pos = [e for e in fetched['result'] if e['side'] == 'Buy'][0]
TypeError: 'NoneType' object is not iterable
Task exception was never retrieved
future: <Task finished name='Task-30' coro=<Bot.on_market_stream_event() done, defined at /home/dario/passivbot/passivbot.py:403> exception=KeyError('long')>
Traceback (most recent call last):
  File "/home/dario/passivbot/passivbot.py", line 418, in on_market_stream_event
    self.update_output_information()
  File "/home/dario/passivbot/passivbot.py", line 469, in update_output_information
    if self.position['long']['size'] != 0.0:
KeyError: 'long'
Task exception was never retrieved
future: <Task finished name='Task-40' coro=<Bot.on_market_stream_event() done, defined at /home/dario/passivbot/passivbot.py:403> exception=KeyError('long')>
Traceback (most recent call last):
  File "/home/dario/passivbot/passivbot.py", line 418, in on_market_stream_event
    self.update_output_information()
  File "/home/dario/passivbot/passivbot.py", line 469, in update_output_information
    if self.position['long']['size'] != 0.0:
KeyError: 'long'
Task exception was never retrieved
future: <Task finished name='Task-41' coro=<Bot.on_market_stream_event() done, defined at /home/dario/passivbot/passivbot.py:403> exception=KeyError('long')>
Traceback (most recent call last):
  File "/home/dario/passivbot/passivbot.py", line 418, in on_market_stream_event
    self.update_output_information()
  File "/home/dario/passivbot/passivbot.py", line 469, in update_output_information
    if self.position['long']['size'] != 0.0:
KeyError: 'long'
Task exception was never retrieved
future: <Task finished name='Task-42' coro=<Bot.on_market_stream_event() done, defined at /home/dario/passivbot/passivbot.py:403> exception=KeyError('long')>
Traceback (most recent call last):
  File "/home/dario/passivbot/passivbot.py", line 418, in on_market_stream_event
    self.update_output_information()
  File "/home/dario/passivbot/passivbot.py", line 469, in update_output_information
    if self.position['long']['size'] != 0.0:
KeyError: 'long'
^C
Stopping passivbot, please wait...

Passivbot was stopped succesfully
```

**Comment by rayures** [comment]
for support, please use the passivbot discord channel #support

**Comment by riodda** [comment]
I did, and people say to use binance.....i don't think there is anything wrong in my command line
`/passivbot$ python3 /home/dario/passivbot/passivbot.py bybit_01 SOLUSDT configs/live/test_1.json` or in my config becouse if I use binance all goes trough, but if use bybit i have all kind of errors in live and in backtest.
This to me looks like a bug but if you tell me that this is not the right place to signal bugs i'm fine.

**Comment by riodda** [comment]
usless to open issues here...
