### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by OreNoMochii** [enarjord/passivbot#317]
Hello I get this error when trying to run the bot. 

Traceback (most recent call last):
  File "/home/ANT.AMAZON.COM/fssobhi/Documents/pso/passivebot/passivbot/passivbot.py", line 428, in on_market_stream_event
    self.update_output_information()
  File "/home/ANT.AMAZON.COM/fssobhi/Documents/pso/passivebot/passivbot/passivbot.py", line 479, in update_output_information
    if self.position['long']['size'] != 0.0:
KeyError: 'long'

Could you please let me know where it comes from ? 

Kindest regards

**Comment by enarjord** [comment]
hello farrabi

does the bot crash after this error?
binance or bybit?
what's the command used to start the bot?

that error comes if self.position is not as expected because it failed to fetch it from exchange
it may be because of wrong api keys or api key permissions
it may be a clock sync issue, usually with windows

**Comment by OreNoMochii** [comment]
Hello the bot crash right after this error. the command to start the bot is python3 passivbot {pair} {config_file_path}
I used it for Binance. 
Might be the api key actually indeed let me check.

**Comment by OreNoMochii** [comment]
it was that indeed. By the way do you know which branch is the latest stable ? There are so many of them haha. Thanks for your reply I think I found the issue.

**Comment by enarjord** [comment]
a tag and a release is made when a version is considered stable
master branch is usually also stable
_dev branches are considered less stable

**Comment by seoeaa** [comment]
same error how did you fix it?

**Comment by mikelike87** [comment]
same error, gents
