### ISSUE TITLE
Backtest not working 🤷‍♂️

### ISSUE THREAD

**Issue by DrakoAI** [enarjord/passivbot#342]
root@DESKTOP-NGT45I9:/mnt/d/DRAKO/passivbot-master# python3 backtest.py results_harmony_search/{date}XXX/xxxxxx_best_config_{long/short}.json -u binance_01 -s ADAUSDT --start_date 2022-05-01 --end_date 2022-06-24
using numba
using numba
fetching market_specific_settings...
linear perpetual
Traceback (most recent call last):
  File "/mnt/d/DRAKO/passivbot-master/procedures.py", line 37, in load_live_config
    live_config = json.load(open(live_config_path))
FileNotFoundError: [Errno 2] No such file or directory: 'results_harmony_search/{date}XXX/xxxxxx_best_config_{long/short}.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "backtest.py", line 210, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "backtest.py", line 150, in main
    live_config = load_live_config(args.live_config_path)
  File "/mnt/d/DRAKO/passivbot-master/procedures.py", line 40, in load_live_config
    raise Exception(f"failed to load live config {live_config_path} {e}")
Exception: failed to load live config results_harmony_search/{date}XXX/xxxxxx_best_config_{long/short}.json [Errno 2] No such file or directory: 'results_harmony_search/{date}XXX/xxxxxx_best_config_{long/short}.json'
root@DESKTOP-NGT45I9:/mnt/d/DRAKO/passivbot-master#

**Comment by DrakoAI** [comment]
I put manually the configuration and if it works but I got some errors:

![image](https://user-images.githubusercontent.com/44076746/175793125-cbe27b47-945b-4078-9574-2ec7bd11a97f.png)
