### ISSUE TITLE
Bybit error

### ISSUE THREAD

**Issue by moafred** [enarjord/passivbot#36]
On the `master` branch, for bybit i needed to cast some data:

```diff
diff --git a/passivbot.py b/passivbot.py
index 06b33c4..147353b 100644
--- a/passivbot.py
+++ b/passivbot.py
@@ -766,10 +766,11 @@ class Bot:
     def init_tick_ema(self, ticks: [dict]):
         print_(['initiating tick ema...'])
         ema_span = self.indicator_settings['tick_ema']['span']
-        ema = ticks[0]['price']
+        ema = float(ticks[0]['price'])
         alpha = 2 / (ema_span + 1)
+
         for t in ticks:
-            ema = ema * (1 - alpha) + t['price'] * alpha
+            ema = ema * (1 - alpha) + float(t['price']) * alpha
         self.indicators['tick_ema'] = ema
         self.indicator_settings['tick_ema']['alpha'] = alpha
         self.indicator_settings['tick_ema']['alpha_'] = 1 - alpha
```

After this few fix, I got this error
```bash
error` starting websocket bybit {"ret_code":34015,"ret_msg":"cross_margin : cannot set leverage which is same to the old leverage","ext_code":"","ext_info":"","result":null,"time_now":"1616775733.292937","rate_limit_status":74,"rate_limit_reset_ms":1616775733291,"rate_limit":75}
```

**Comment by enarjord** [comment]
@moafred it's more a warning than an error.  it tries to set lev to the same as it already is.  the bot starts does it not?

about the need to int() some vals, i never had that error myself...

**Comment by moafred** [comment]
> @moafred it's more a warning than an error. it tries to set lev to the same as it already is. the bot starts does it not?

Okay :)

ps: i'm on ubuntu.

---

It starts but cannot evaluate the position, so it gos to an infinite loop.

There is another issue about casting but i don't find where (i'm not a python dev and don't take time yet to go deeper)
```

Starting bybit frederic_oudry
not using numba
2021-03-26T18:30:39  settings for user frederic_oudry not found, using default settings

loaded settings:
{'balance_pct': 0.537,
 'config_name': 'btc_nostops_closest_liq_10%',
 'cross_mode': True,
 'ddown_factor': 0.298,
 'entry_qty_pct': 0.10101,
 'grid_coefficient': 203.6,
 'grid_spacing': 0.00152,
 'indicator_settings': {'do_long': True,
                        'do_shrt': True,
                        'funding_fee_collect_mode': False,
                        'ohlcv_rsi': {'n_periods': 21, 'period_ms': 1800000},
                        'tick_ema': {'span': 61499.0, 'spread': 0.0133}},
 'key': 'a331d60fe8e76f39d957d74d083b4191f61e7817c5b0ab25d1d89cc3ccc8cbb0',
 'leverage': 19.0,
 'logging_level': 0,
 'market_stop_loss': False,
 'max_markup': 0.01135,
 'min_close_qty_multiplier': 0.15,
 'min_markup': 0.00066,
 'n_close_orders': 18.0,
 'n_entry_orders': 8,
 'stop_loss_liq_diff': 0.07,
 'stop_loss_pos_price_diff': 0.9,
 'stop_loss_pos_reduction': 0.01,
 'symbol': 'BTCUSD'}
error with update position can't multiply sequence by non-int of type 'float'
2021-03-26T18:30:39  wss://stream.bybit.com/realtime
2021-03-26T18:30:40  fetched trades BTCUSD 273875584 2021-03-26T17:30:40.652000
2021-03-26T18:30:40  fetched trades BTCUSD 273873584 2021-03-26T17:23:18.268000
2021-03-26T18:30:40  fetched trades BTCUSD 273871584 2021-03-26T17:18:14.190000
2021-03-26T18:30:40  fetched trades BTCUSD 273874584 2021-03-26T17:27:50.584000
2021-03-26T18:30:40  fetched trades BTCUSD 273872584 2021-03-26T17:20:06.334000
2021-03-26T18:30:40  fetched trades BTCUSD 273870584 2021-03-26T17:16:54.466000
2021-03-26T18:30:40  fetched trades BTCUSD 273868584 2021-03-26T17:11:20.986000
2021-03-26T18:30:40  fetched trades BTCUSD 273850584 2021-03-26T16:47:30.701000
2021-03-26T18:30:40  fetched trades BTCUSD 273866584 2021-03-26T17:09:00.345000
2021-03-26T18:30:40  fetched trades BTCUSD 273869584 2021-03-26T17:14:25.888000
2021-03-26T18:30:40  fetched trades BTCUSD 273865584 2021-03-26T17:07:07.980000
2021-03-26T18:30:40  fetched trades BTCUSD 273867584 2021-03-26T17:09:59.215000
2021-03-26T18:30:40  fetched trades BTCUSD 273863584 2021-03-26T17:06:14.823000
2021-03-26T18:30:40  fetched trades BTCUSD 273853584 2021-03-26T16:50:45.879000
2021-03-26T18:30:40  fetched trades BTCUSD 273852584 2021-03-26T16:49:19.218000
2021-03-26T18:30:40  fetched trades BTCUSD 273833584 2021-03-26T16:33:27.210000
2021-03-26T18:30:40  fetched trades BTCUSD 273844584 2021-03-26T16:43:09.900000
2021-03-26T18:30:40  fetched trades BTCUSD 273839584 2021-03-26T16:37:21.559000
2021-03-26T18:30:40  fetched trades BTCUSD 273851584 2021-03-26T16:48:48.603000
2021-03-26T18:30:40  fetched trades BTCUSD 273859584 2021-03-26T17:00:43.390000
2021-03-26T18:30:40  fetched trades BTCUSD 273854584 2021-03-26T16:52:12.804000
2021-03-26T18:30:40  fetched trades BTCUSD 273861584 2021-03-26T17:03:20.342000
2021-03-26T18:30:40  fetched trades BTCUSD 273849584 2021-03-26T16:46:06.399000
2021-03-26T18:30:40  fetched trades BTCUSD 273835584 2021-03-26T16:34:04.458000
2021-03-26T18:30:40  fetched trades BTCUSD 273840584 2021-03-26T16:37:59.993000
2021-03-26T18:30:40  fetched trades BTCUSD 273860584 2021-03-26T17:01:38.056000
2021-03-26T18:30:40  fetched trades BTCUSD 273858584 2021-03-26T16:59:54.940000
2021-03-26T18:30:40  fetched trades BTCUSD 273841584 2021-03-26T16:38:30.070000
2021-03-26T18:30:40  fetched trades BTCUSD 273862584 2021-03-26T17:05:38.619000
2021-03-26T18:30:40  fetched trades BTCUSD 273842584 2021-03-26T16:40:14.097000
2021-03-26T18:30:40  fetched trades BTCUSD 273837584 2021-03-26T16:36:11.119000
2021-03-26T18:30:40  fetched trades BTCUSD 273843584 2021-03-26T16:42:02.652000
2021-03-26T18:30:40  fetched trades BTCUSD 273848584 2021-03-26T16:45:08.949000
2021-03-26T18:30:40  fetched trades BTCUSD 273855584 2021-03-26T16:54:18.510000
2021-03-26T18:30:40  fetched trades BTCUSD 273846584 2021-03-26T16:43:50.703000
2021-03-26T18:30:40  fetched trades BTCUSD 273845584 2021-03-26T16:43:24.666000
2021-03-26T18:30:40  fetched trades BTCUSD 273838584 2021-03-26T16:36:48.200000
2021-03-26T18:30:40  fetched trades BTCUSD 273864584 2021-03-26T17:06:18.155000
2021-03-26T18:30:40  fetched trades BTCUSD 273856584 2021-03-26T16:55:17.734000
2021-03-26T18:30:40  fetched trades BTCUSD 273847584 2021-03-26T16:44:09.281000
2021-03-26T18:30:40  fetched trades BTCUSD 273828584 2021-03-26T16:31:17.104000
2021-03-26T18:30:40  fetched trades BTCUSD 273857584 2021-03-26T16:56:57.893000
2021-03-26T18:30:40  fetched trades BTCUSD 273829584 2021-03-26T16:31:25.251000
2021-03-26T18:30:41  fetched trades BTCUSD 273831584 2021-03-26T16:32:21.477000
2021-03-26T18:30:41  fetched trades BTCUSD 273827584 2021-03-26T16:31:08.992000
2021-03-26T18:30:41  fetched trades BTCUSD 273834584 2021-03-26T16:33:30.474000
2021-03-26T18:30:41  fetched trades BTCUSD 273832584 2021-03-26T16:32:43.104000
2021-03-26T18:30:41  fetched trades BTCUSD 273836584 2021-03-26T16:35:17.905000
2021-03-26T18:30:41  fetched trades BTCUSD 273830584 2021-03-26T16:31:54.873000
2021-03-26T18:30:41  fetched trades BTCUSD 273826584 2021-03-26T16:30:43.040000
2021-03-26T18:30:41  initiating tick ema...
error starting websocket bybit {"ret_code":34015,"ret_msg":"cross_margin : cannot set leverage which is same to the old leverage","ext_code":"","ext_info":"","result":null,"time_now":"1616779842.296041","rate_limit_status":74,"rate_limit_reset_ms":1616779842294,"rate_limit":75}
Task exception was never retrieved
future: <Task finished name='Task-166' coro=<Bot.decide() done, defined at /home/frederic/workspace/crypto/trading-bots/passivbot_futures_v2/passivbot.py:727> exception=KeyError('size')>
Traceback (most recent call last):
  File "/home/frederic/workspace/crypto/trading-bots/passivbot_futures_v2/passivbot.py", line 748, in decide
    if self.position['size'] == 0:
KeyError: 'size'
Task exception was never retrieved
future: <Task finished name='Task-168' coro=<Bot.decide() done, defined at /home/frederic/workspace/crypto/trading-bots/passivbot_futures_v2/passivbot.py:727> exception=KeyError('size')>
Traceback (most recent call last):
  File "/home/frederic/workspace/crypto/trading-bots/passivbot_futures_v2/passivbot.py", line 748, in decide
    if self.position['size'] == 0:
KeyError: 'size'
Task exception was never retrieved
future: <Task finished name='Task-169' coro=<Bot.decide() done, defined at /home/frederic/workspace/crypto/trading-bots/passivbot_futures_v2/passivbot.py:727> exception=KeyError('size')>
Traceback (most recent call last):
  File "/home/frederic/workspace/crypto/trading-bots/passivbot_futures_v2/passivbot.py", line 748, in decide
    if self.position['size'] == 0:
KeyError: 'size'
Task exception was never retrieved
future: <Task finished name='Task-169' coro=<Bot.decide() done, defined at /home/frederic/workspace/crypto/trading-bots/passivbot_futures_v2/passivbot.py:727> exception=KeyError('size')>
Traceback (most recent call last):
  File "/home/frederic/workspace/crypto/trading-bots/passivbot_futures_v2/passivbot.py", line 748, in decide
    if self.position['size'] == 0:
KeyError: 'size'
Task exception was never retrieved
future: <Task finished name='Task-169' coro=<Bot.decide() done, defined at /home/frederic/workspace/crypto/trading-bots/passivbot_futures_v2/passivbot.py:727> exception=KeyError('size')>
Traceback (most recent call last):
  File "/home/frederic/workspace/crypto/trading-bots/passivbot_futures_v2/passivbot.py", line 748, in decide
    if self.position['size'] == 0:
KeyError: 'size'
Task exception was never retrieved
future: <Task finished name='Task-169' coro=<Bot.decide() done, defined at /home/frederic/workspace/crypto/trading-bots/passivbot_futures_v2/passivbot.py:727> exception=KeyError('size')>
Traceback (most recent call last):
  File "/home/frederic/workspace/crypto/trading-bots/passivbot_futures_v2/passivbot.py", line 748, in decide
    if self.position['size'] == 0:
KeyError: 'size'
```

**Comment by enarjord** [comment]
v3.2 only works with hedge mode at this time

for bybit that's only symbols BTCUSDM21 and BTCUSDU21 in inverse futures

it won't work with any inverse perpetual contract or USDT margined contract.  support for those may be added in future

**Comment by dclausen** [comment]
I'm running passivbot v2.1.0 on mac OSX 11.2.1 python 3.8.0 for backtesting and all is fine. I'm trying to run live in a hosted ubuntu linux server running 20.04 python 3.8.5 passivbot v2.1.0 and I'm getting the same float errors. If I fix them using moafred's patch, I also get the KeyError: 'size' on line 748. That error is occurring because self.position is {}.

**Comment by moafred** [comment]
@dclausen you can fix the issue just [be forcing the version of ccxt to 1.42.38 ](https://discord.com/channels/804826506551230475/804836050111168583/825104876782485555), there is a change of contract in the 1.42.39.

**Comment by dclausen** [comment]
confirmed that downgrading ccxt works for me. thanks @moafred !
