### ISSUE TITLE
okx - shitcoins superlow volume

### ISSUE THREAD

**Issue by ilaykim** [enarjord/passivbot#372]
There are no open positions.

```
2023-01-08T18:12:35 INFO     starting passivbot in ohlcv mode, using REST API only and updating once a minute
2023-01-08T18:12:36 INFO     {'code': '0', 'data': [{'instId': 'DOME-USDT-SWAP', 'lever': '75', 'mgnMode': 'cross', 'posSide': ''}], 'msg': ''}
2023-01-08T18:12:36 INFO     {'code': '0', 'data': [{'instId': 'DOME-USDT-SWAP', 'lever': '75', 'mgnMode': 'cross', 'posSide': ''}], 'msg': ''}
okx {"code":"59000","data":[],"msg":"Settings failed. Close any open positions or orders before modifying settings."}
2023-01-08T18:12:38 INFO     starting bot...
2023-01-08T18:13:00 INFO     heartbeat DOME/USDT:USDT
2023-01-08T18:13:00 INFO     long: 0.0 @ 0.0 lWE: 0.0000 pprc diff -1.000 EMAs: [0.0024679, 0.0024768, 0.002481] e 0.0 @ 0.0 | c 0.0 @ 0.0
2023-01-08T18:13:00 INFO     short: 0.0 @ 0.0 sWE: 0.0000 pprc diff 1.000 EMAs: [0.002478, 0.002478, 0.002478] e 0.0 @ 0.0 | c 0.0 @ 0.0
2023-01-08T18:13:00 INFO     balance: 99.998 equity: 99.998 last price: 0.00244 liq: 0.0
error executing order None okx {"code":"1","data":[{"clOrdId":"longientry53db160fab9f4f64a75331","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortientry77f9e56913954953899c1","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""}],"msg":"All operations failed"}
returned: None
Traceback (most recent call last):
  File "/home/bot/testing/passivbot/okx.py", line 213, in execute_orders
    executed = await self.okx.private_post_trade_batch_orders(params=to_execute)
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 1125, in request
    return await self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 1122, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 163, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/okx.py", line 5045, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 1343, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidOrder: okx {"code":"1","data":[{"clOrdId":"longientry53db160fab9f4f64a75331","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortientry77f9e56913954953899c1","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""}],"msg":"All operations failed"}
countdown: 47.0 last price: 0.00244
```

Another super small coin

```
2023-01-08T18:08:58 INFO     starting bot...
2023-01-08T18:09:00 INFO     heartbeat KISHU/USDT:USDT
2023-01-08T18:09:00 INFO     long: 0.0 @ 0.0 lWE: 0.0000 pprc diff -1.000 EMAs: [3.5809e-10, 3.5818e-10, 3.5832e-10] e 0.0 @ 0.0 | c 0.0 @ 0.0
2023-01-08T18:09:00 INFO     short: 0.0 @ 0.0 sWE: 0.0000 pprc diff 1.000 EMAs: [3.5873e-10, 3.5873e-10, 3.5873e-10] e 0.0 @ 0.0 | c 0.0 @ 0.0
2023-01-08T18:09:00 INFO     balance: 99.998 equity: 99.998 last price: 3.58e-10 liq: 0.0
error executing order None okx {"code":"1","data":[{"clOrdId":"longientryd308dde9520b441c89f2b0","ordId":"","sCode":"51000","sMsg":"Parameter px  error","tag":""},{"clOrdId":"shortientry9d7fe5c555af4e46b6b4a","ordId":"","sCode":"51000","sMsg":"Parameter px  error","tag":""}],"msg":""}
returned: None
Traceback (most recent call last):
  File "/home/bot/testing/passivbot/okx.py", line 213, in execute_orders
    executed = await self.okx.private_post_trade_batch_orders(params=to_execute)
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 1125, in request
    return await self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 1122, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 163, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/okx.py", line 5045, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 1343, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: okx {"code":"1","data":[{"clOrdId":"longientryd308dde9520b441c89f2b0","ordId":"","sCode":"51000","sMsg":"Parameter px  error","tag":""},{"clOrdId":"shortientry9d7fe5c555af4e46b6b4a","ordId":"","sCode":"51000","sMsg":"Parameter px  error","tag":""}],"msg":""}
countdown: 50.5 last price: 3.58e-10

```

**Comment by enarjord** [comment]
same problem as issue #370 , fixed in commit https://github.com/enarjord/passivbot/commit/afd3b690aab3e3a755ca87a13353602de021b771
