### ISSUE TITLE
sCode: 51004 Order amount exceeds the current tier limit.

### ISSUE THREAD

**Issue by ilaykim** [enarjord/passivbot#373]
(pulled again of course - previous issue seems to be working in 1 coin) 

But now getting this in another coin. (available 94 USDT)

```
2023-01-09T17:04:40 INFO     starting bot...
2023-01-09T17:05:00 INFO     heartbeat AGLD/USDT:USDT
2023-01-09T17:05:00 INFO     long: 0.0 @ 0.0 lWE: 0.0000 pprc diff -1.000 EMAs: [0.27436, 0.27617, 0.27789] e 0.0 @ 0.0 | c 0.0 @ 0.0
2023-01-09T17:05:00 INFO     short: 1.0 @ 0.2674 sWE: 0.0026 pprc diff 0.052 EMAs: [0.2796, 0.2796, 0.2796] e 0.0 @ 0.0 | c 1.0 @ 0.2619
2023-01-09T17:05:00 INFO     balance: 102.024 equity: 102.01 last price: 0.2813 liq: 0.0
error executing order None [{'side': 'sell', 'position_side': 'short', 'qty': 1.0, 'price': 0.2889, 'type': 'limit', 'reduce_only': False, 'custom_id': 'short_primary_rentry'}, {'side': 'buy', 'position_side': 'long', 'qty': 1.0, 'price': 0.2725, 'type': 'limit', 'reduce_only': False, 'custom_id': 'long_ientry'}, {'side': 'sell', 'position_side': 'short', 'qty': 2.0, 'price': 0.3083, 'type': 'limit', 'reduce_only': False, 'custom_id': 'short_primary_rentry'}, {'side': 'sell', 'position_side': 'short', 'qty': 2.0, 'price': 0.3258, 'type': 'limit', 'reduce_only': False, 'custom_id': 'short_primary_rentry'}, {'side': 'sell', 'position_side': 'short', 'qty': 3.0, 'price': 0.3417, 'type': 'limit', 'reduce_only': False, 'custom_id': 'short_primary_rentry'}, {'side': 'sell', 'position_side': 'short', 'qty': 3.0, 'price': 0.356, 'type': 'limit', 'reduce_only': False, 'custom_id': 'short_primary_rentry'}, {'side': 'sell', 'position_side': 'short', 'qty': 4.0, 'price': 0.3689, 'type': 'limit', 'reduce_only': False, 'custom_id': 'short_primary_rentry'}, {'side': 'sell', 'position_side': 'short', 'qty': 5.0, 'price': 0.3805, 'type': 'limit', 'reduce_only': False, 'custom_id': 'short_primary_rentry'}, {'side': 'sell', 'position_side': 'short', 'qty': 6.0, 'price': 0.391, 'type': 'limit', 'reduce_only': False, 'custom_id': 'short_primary_rentry'}, {'side': 'sell', 'position_side': 'short', 'qty': 7.0, 'price': 0.4005, 'type': 'limit', 'reduce_only': False, 'custom_id': 'short_primary_rentry'}, {'side': 'sell', 'position_side': 'short', 'qty': 8.0, 'price': 0.4091, 'type': 'limit', 'reduce_only': False, 'custom_id': 'short_primary_rentry'}, {'side': 'sell', 'position_side': 'short', 'qty': 9.0, 'price': 0.4169, 'type': 'limit', 'reduce_only': False, 'custom_id': 'short_primary_rentry'}] okx {"code":"1","data":[{"clOrdId":"shortprimaryrentryeb4718bf8b7a48","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"longientry57ae31c687824719a9d406","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry3a98823301b645","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry40ef6f41a9554f","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry19c315872dc748","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry36fb7cc7eeec41","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentrya8af292994584b","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry094eadf9eefe40","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentrya6f55e25b7c44e","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry000f194181824d","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry193c4ce3517343","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry5b80def9b15a44","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""}],"msg":"All operations failed"}
returned: None
Traceback (most recent call last):
  File "/home/bot/testing/passivbot/okx.py", line 213, in execute_orders
    executed = await self.okx.private_post_trade_batch_orders(params=to_execute)
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 1125, in request
    return await self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 1122, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 163, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/okx.py", line 5045, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/home/bot/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 1343, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidOrder: okx {"code":"1","data":[{"clOrdId":"shortprimaryrentryeb4718bf8b7a48","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"longientry57ae31c687824719a9d406","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry3a98823301b645","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry40ef6f41a9554f","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry19c315872dc748","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry36fb7cc7eeec41","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentrya8af292994584b","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry094eadf9eefe40","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentrya6f55e25b7c44e","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry000f194181824d","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry193c4ce3517343","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""},{"clOrdId":"shortprimaryrentry5b80def9b15a44","ordId":"","sCode":"51004","sMsg":"Order amount exceeds the current tier limit. Please lower the leverage. ","tag":""}],"msg":"All operations failed"}
countdown: 39.6 last price: 0.2813
```

**Comment by ilaykim** [comment]
fixed by lowering leverage.

position size was too small. bad config on my end.
