### ISSUE TITLE
Not working with bybit since 2023-07-11

### ISSUE THREAD

**Issue by smartlabtamu** [enarjord/passivbot#410]
I have been running a bunch of bots for trading USDT perpetual contracts on bybit for sometime without any issues. Since yesterday however, when I run the bot (python3 passivbot.py bybitbot BTCUSDT configs/live/btc_1x_long_1-10.json) the code gives the following error. I suspect the issue is due to the recent API upgrade to v5. If somebody can resolve the issue, that would be great. 

Thanks.

Error

2023-07-12T16:59:27 ERROR    There was an error starting the bot: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/root/passivbot/passivbot.py", line 1984, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/root/passivbot/passivbot.py", line 1951, in main
    bot = await create_bybit_bot(config)
  File "/home/root/passivbot/procedures.py", line 313, in create_bybit_bot
    await bot._init()
  File "/home/root/passivbot/exchanges/bybit.py", line 152, in _init
    info = await self.public_get(self.endpoints["exchange_info"])
  File "/home/root/passivbot/exchanges/bybit.py", line 205, in public_get
    return json.loads(result)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-12T16:59:27 ERROR    Passivbot was stopped succesfully
root@instance-1:~/passivbot$

**Comment by enarjord** [comment]
my bybit bots run fine and i haven't upgraded to v5 unified API

might be some other issue, maybe expired api key or bybit discontinuing derivatives support for some countries

added a couple of extra error prints. try pulling latest and run again

**Comment by smartlabtamu** [comment]
Thank you, enarjord! I checked the error message and indeed its the latter. I changed the google server location and now it works fine.
