### ISSUE TITLE
error fetching ohlcvs for XLMUSDT

### ISSUE THREAD

**Issue by memorycancel** [enarjord/passivbot#440]
Hi! After config done, I run `python3 harmony_search.py -u ba -s XLMUSDT  --start_date 2023-06-01 --end_date 2023-07-01`
what's the problem?

then got:

```shell                                     
using numba
using numba
using numba
using numba
fetching market_specific_settings for XLMUSDT...

market_type                                 futures
user                                        ba
latency_simulation_ms                       1000
starting_balance                            10000
start_date                                  2023-06-01
end_date                                    2023-07-01
slim_analysis                               True
base_dir                                    backtests
ohlcv                                       True
adg_n_subdivisions                          10
enable_interactive_plot                     False
plot_theme                                  light
plot_candles_interval                       1m
spot                                        False
exchange                                    binance
session_name                                2023-06-01_2023-07-01
symbol                                      XLMUSDT
caches_dirpath                              backtests/binance/XLMUSDT/caches/
plots_dirpath                               backtests/binance/XLMUSDT/plots/
c_mult                                      1.0
hedge_mode                                  True
inverse                                     False
maker_fee                                   0.0002
min_cost                                    5.0
min_qty                                     1.0
price_step                                  1e-05
qty_step                                    1.0
taker_fee                                   0.0004
n_harmonies                                 32
hm_considering_rate                         0.9
bandwidth                                   0.07
pitch_adjusting_rate                        0.24
n_particles                                 36
w                                           0.73
c0                                          1
c1                                          0.4
algorithm                                   particle_swarm_optimization
n_cpus                                      6
iters                                       4000
n_backtest_slices                           5
maximum_drawdown_max_long                   0.25
maximum_drawdown_max_short                  0.25
maximum_drawdown_1pct_worst_mean_long       0.1
maximum_drawdown_1pct_worst_mean_short      0.1
maximum_pa_distance_std_long                -1
maximum_pa_distance_std_short               -1
maximum_pa_distance_mean_long               -1
maximum_pa_distance_mean_short              -1
maximum_pa_distance_1pct_worst_mean_long    -0.1
maximum_pa_distance_1pct_worst_mean_short   -0.1
maximum_loss_profit_ratio_long              0.15
maximum_loss_profit_ratio_short             0.15
maximum_hrs_stuck_max_long                  120
maximum_hrs_stuck_max_short                 120
maximum_exposure_ratios_mean_long           -1
maximum_exposure_ratios_mean_short          -1
maximum_time_at_max_exposure_long           -1
maximum_time_at_max_exposure_short          -1
clip_threshold                              0
do_long                                     True
do_short                                    True
backwards_tp_long                           True
backwards_tp_short                          True
passivbot_mode                              recursive_grid
results_fpath                               results_particle_swarm_optimization_recursive_grid/2024-03-21T17-51-15_XLMUSDT/
config_name                                 recursive_grid_test
logging_level                               0

fetching data XLMUSDT
fetching market_specific_settings for XLMUSDT...
error fetching ohlcvs for XLMUSDT binanceusdm GET https://fapi.binance.com/fapi/v1/exchangeInfo
dumped first ohlcv timestamp cache for binanceusdm ['XLMUSDT']
Traceback (most recent call last):
  File "/home/tommy/codes/passivbot/harmony_search.py", line 426, in <module>
    asyncio.run(main_(algorithm="harmony_search"))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/tommy/codes/passivbot/optimize.py", line 344, in main
    await run_opt(args, config)
  File "/home/tommy/codes/passivbot/optimize.py", line 408, in run_opt
    data = await load_hlc_cache(
  File "/home/tommy/codes/passivbot/downloader.py", line 1290, in load_hlc_cache
    df = await download_ohlcvs_binance(symbol, inverse, start_date, end_date, spot)
  File "/home/tommy/codes/passivbot/downloader.py", line 1163, in download_ohlcvs_binance
    start_ts = (await get_first_ohlcv_timestamps(symbols=[symbol]))[symbol]
KeyError: 'XLMUSDT'
```

**Comment by hebe061103** [comment]
I am the same question too,I think maybe it is a network problem! Where are you from?

**Comment by Fred3343** [comment]
> I am the same question too,I think maybe it is a network problem! Where are you from?

How did you deal with this problem? I'm still the problem

**Comment by Fred3343** [comment]
> Hi! After config done, I run `python3 harmony_search.py -u ba -s XLMUSDT --start_date 2023-06-01 --end_date 2023-07-01` what's the problem?
> 
> then got:
> 
> ```shell
> using numba
> using numba
> using numba
> using numba
> fetching market_specific_settings for XLMUSDT...
> 
> market_type                                 futures
> user                                        ba
> latency_simulation_ms                       1000
> starting_balance                            10000
> start_date                                  2023-06-01
> end_date                                    2023-07-01
> slim_analysis                               True
> base_dir                                    backtests
> ohlcv                                       True
> adg_n_subdivisions                          10
> enable_interactive_plot                     False
> plot_theme                                  light
> plot_candles_interval                       1m
> spot                                        False
> exchange                                    binance
> session_name                                2023-06-01_2023-07-01
> symbol                                      XLMUSDT
> caches_dirpath                              backtests/binance/XLMUSDT/caches/
> plots_dirpath                               backtests/binance/XLMUSDT/plots/
> c_mult                                      1.0
> hedge_mode                                  True
> inverse                                     False
> maker_fee                                   0.0002
> min_cost                                    5.0
> min_qty                                     1.0
> price_step                                  1e-05
> qty_step                                    1.0
> taker_fee                                   0.0004
> n_harmonies                                 32
> hm_considering_rate                         0.9
> bandwidth                                   0.07
> pitch_adjusting_rate                        0.24
> n_particles                                 36
> w                                           0.73
> c0                                          1
> c1                                          0.4
> algorithm                                   particle_swarm_optimization
> n_cpus                                      6
> iters                                       4000
> n_backtest_slices                           5
> maximum_drawdown_max_long                   0.25
> maximum_drawdown_max_short                  0.25
> maximum_drawdown_1pct_worst_mean_long       0.1
> maximum_drawdown_1pct_worst_mean_short      0.1
> maximum_pa_distance_std_long                -1
> maximum_pa_distance_std_short               -1
> maximum_pa_distance_mean_long               -1
> maximum_pa_distance_mean_short              -1
> maximum_pa_distance_1pct_worst_mean_long    -0.1
> maximum_pa_distance_1pct_worst_mean_short   -0.1
> maximum_loss_profit_ratio_long              0.15
> maximum_loss_profit_ratio_short             0.15
> maximum_hrs_stuck_max_long                  120
> maximum_hrs_stuck_max_short                 120
> maximum_exposure_ratios_mean_long           -1
> maximum_exposure_ratios_mean_short          -1
> maximum_time_at_max_exposure_long           -1
> maximum_time_at_max_exposure_short          -1
> clip_threshold                              0
> do_long                                     True
> do_short                                    True
> backwards_tp_long                           True
> backwards_tp_short                          True
> passivbot_mode                              recursive_grid
> results_fpath                               results_particle_swarm_optimization_recursive_grid/2024-03-21T17-51-15_XLMUSDT/
> config_name                                 recursive_grid_test
> logging_level                               0
> 
> fetching data XLMUSDT
> fetching market_specific_settings for XLMUSDT...
> error fetching ohlcvs for XLMUSDT binanceusdm GET https://fapi.binance.com/fapi/v1/exchangeInfo
> dumped first ohlcv timestamp cache for binanceusdm ['XLMUSDT']
> Traceback (most recent call last):
>   File "/home/tommy/codes/passivbot/harmony_search.py", line 426, in <module>
>     asyncio.run(main_(algorithm="harmony_search"))
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "/home/tommy/codes/passivbot/optimize.py", line 344, in main
>     await run_opt(args, config)
>   File "/home/tommy/codes/passivbot/optimize.py", line 408, in run_opt
>     data = await load_hlc_cache(
>   File "/home/tommy/codes/passivbot/downloader.py", line 1290, in load_hlc_cache
>     df = await download_ohlcvs_binance(symbol, inverse, start_date, end_date, spot)
>   File "/home/tommy/codes/passivbot/downloader.py", line 1163, in download_ohlcvs_binance
>     start_ts = (await get_first_ohlcv_timestamps(symbols=[symbol]))[symbol]
> KeyError: 'XLMUSDT'
> ```

How did you deal with it?
