### ISSUE TITLE
Error: error fetching open orders string indices must be integers

### ISSUE THREAD

**Issue by chepo92** [enarjord/passivbot#441]
I get this error when starting passivbot

Trace: 
```2024-03-21T20:22:59 INFO     starting passivbot in ohlcv mode, using REST API only and updating once a minute
2024-03-21T20:22:59 INFO     starting bot...
2024-03-21T20:23:30 INFO     heartbeat INJUSDT  
2024-03-21T20:23:30 ERROR    error with printing heartbeat 'long'
2024-03-21T20:23:31 ERROR    error fetching open orders string indices must be integers
Traceback (most recent call last):
  File "/passivbot/exchanges/binance.py", line 304, in fetch_open_orders
    return [
  File "/passivbot/exchanges/binance.py", line 306, in <listcomp>
    "order_id": int(e["orderId"]),
TypeError: string indices must be integers
2024-03-21T20:23:31 ERROR    error with update open orders 'bool' object is not iterable
Traceback (most recent call last):
  File "/passivbot/passivbot.py", line 360, in update_open_orders
    open_orders = [x for x in open_orders if x["symbol"] == self.symbol]
TypeError: 'bool' object is not iterable
Traceback (most recent call last):
  File "/passivbot/exchanges/binance.py", line 506, in fetch_latest_fills
    fills += [
  File "/passivbot/exchanges/binance.py", line 508, in <listcomp>
    "order_id": elm["orderId"],
TypeError: string indices must be integers
2024-03-21T20:23:31 ERROR    error fetching pos or balance 0
Traceback (most recent call last):
  File "/passivbot/exchanges/binance.py", line 337, in fetch_position
    assert all(
  File "/passivbot/exchanges/binance.py", line 338, in <genexpr>
    key in positions[0] for key in ["symbol", "positionAmt", "entryPrice"]
KeyError: 0
2024-03-21T20:23:31 ERROR    error with update position 
Traceback (most recent call last):
  File "/passivbot/passivbot.py", line 428, in update_position
    assert position is not None
AssertionError
```

Any clue?

**Comment by chepo92** [comment]
solved, bot wasn't having access to API due IP restriction and recent IP change in my ISP 

after a while running the bot appeared an error-hint 
`returned: {'code': -2015, 'msg': 'Invalid API-key, IP, or permissions for action, request ip: x.x.x.'}`

bot may catch the error and throw some hints, as orders are empty, may suggest to check conection and api access

**Comment by LaAlquimia** [comment]
@chepo92 Must be great for binace ip blocks after serveral bots
