### ISSUE TITLE
Our country needs proxy

### ISSUE THREAD

**Issue by sunhotblaze** [enarjord/passivbot#449]
```
fetching data ETHUSDT
fetching market_specific_settings for ETHUSDT...
error fetching ohlcvs for ETHUSDT binanceusdm GET https://fapi.binance.com/fapi/v1/exchangeInfo
dumped first ohlcv timestamp cache for binanceusdm ['ETHUSDT']
Traceback (most recent call last):
  File "/root/passivbot/harmony_search.py", line 434, in <module>
    asyncio.run(main_(algorithm="harmony_search"))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/root/passivbot/optimize.py", line 344, in main
    await run_opt(args, config)
  File "/root/passivbot/optimize.py", line 408, in run_opt
    data = await load_hlc_cache(
  File "/root/passivbot/downloader.py", line 1290, in load_hlc_cache
    df = await download_ohlcvs_binance(symbol, inverse, start_date, end_date, spot)
  File "/root/passivbot/downloader.py", line 1163, in download_ohlcvs_binance
    start_ts = (await get_first_ohlcv_timestamps(symbols=[symbol]))[symbol]
KeyError: 'ETHUSDT'
```
Hope to add network proxy configuration

**Comment by Frank9932** [comment]
You can use the VPS which is recommended in the readme section of this project already or modify the CCXT related code to add proxy settings by yourself

**Comment by nexgen** [comment]
Looks like the ccxt instance is initiated from multiple places. Isn't there a way to add proxy in one location which will be used by ccxt?
