### ISSUE TITLE
Message Failed to initialize telegram

### ISSUE THREAD

**Issue by ghostnetrn** [enarjord/passivbot#83]
failed to initialize telegram
Traceback (most recent call last):
  File "passivbot.py", line 641, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "passivbot.py", line 636, in main
    signal.signal(signal.SIGINT, telegram.exit)
AttributeError: 'NoneType' object has no attribute 'exit'

**Comment by ghostnetrn** [comment]
Hi,
Python Packages (Ok)
Config api-keys
"binance_01" : {
        "exchange": "binance",
        "key": "key",
        "secret": "secret",
        "telegram": {
            "enabled": true,
            "token": "",
            "chat_id": ""
        }

Messages are received at Telegram, but the bot stops at that message.

**Comment by ghostnetrn** [comment]
By clicking on the show_config button

traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/dispatcher.py", line 447, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "/home/binance/telegram_bot.py", line 93, in show_config
    repo = git.Repo(search_parent_directories=True)
  File "/usr/local/lib/python3.8/dist-packages/git/repo/base.py", line 181, in __init__
    raise InvalidGitRepositoryError(epath)

**Comment by ghostnetrn** [comment]
without container

**Comment by ghostnetrn** [comment]
starting it from the git clone root (master)

**Comment by ghostnetrn** [comment]
fatal: not a git repository (or any of the parent directories): .git

**Comment by ghostnetrn** [comment]
Thanks!
