### ISSUE TITLE
Bot doesn't restart on Connection reset by peer

### ISSUE THREAD

**Issue by jeet2k123** [enarjord/passivbot#87]
I've seen a lot of Connection reset by peer during backtesting while fetching historical data.(Maybe exchange is disconnecting)
The backtester(optimzer.py) then stops fetching data and starts doing iterations.

Now while start_bot.py is throwing same error but its not restarting...

```
2021-05-05T17:38:37  DENTUSDT long 507.0 @ 0.00987 close @ 0.009985 enter @ 0.00975 || shrt 0.0 @ 0.0 close @ 0.0 enter @ 0.009951 || last 0.009854 liq 0.0 sl trig 0.0 ema 0.00991 bal 102.1 equity 102.1 v. 0.02771823   error with update
open orders [Errno 104] Connection reset by peer
error with update position [Errno 104] Connection reset by peer
flushing update_position
2021-05-05T17:38:47  DENTUSDT long 507.0 @ 0.00987 close @ 0.009985 enter @ 0.00975 || shrt 0.0 @ 0.0 close @ 0.0 enter @ 0.009951 || last 0.009851 liq 0.0 sl trig 0.0 ema 0.00991 bal 102.1 equity 102.1 v. 0.02771377   Traceback (most re
cent call last):
  File "/opt/passivbot/.env/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/opt/passivbot/.env/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/opt/passivbot/.env/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/opt/passivbot/.env/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/opt/passivbot/.env/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

Traceback (most recent call last):
  File "/opt/passivbot/.env/lib/python3.8/site-packages/telegram/ext/updater.py", line 520, in _network_loop_retry
    if not action_cb():
  File "/opt/passivbot/.env/lib/python3.8/site-packages/telegram/ext/updater.py", line 471, in polling_action_cb
    updates = self.bot.get_updates(
  File "/opt/passivbot/.env/lib/python3.8/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/opt/passivbot/.env/lib/python3.8/site-packages/telegram/bot.py", line 2761, in get_updates
    result = self._post(
  File "/opt/passivbot/.env/lib/python3.8/site-packages/telegram/bot.py", line 259, in _post
    return self.request.post(
  File "/opt/passivbot/.env/lib/python3.8/site-packages/telegram/utils/request.py", line 350, in post
    result = self._request_wrapper(
  File "/opt/passivbot/.env/lib/python3.8/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/getUpdates (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa31ce5a0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

**Comment by raven-kus** [comment]
@jeet2k123 Hello mate, you leaked your bot token

**Comment by jeet2k123** [comment]
ok..thanks...removed it

**Comment by eliafino** [comment]
@jeet2k123 Please @enarjord remove this post in telegram group

**Comment by jeet2k123** [comment]
works now..
