### ISSUE TITLE
IncompleteReadError

### ISSUE THREAD

**Issue by jeet2k123** [enarjord/passivbot#89]
2021-05-06T23:22:22  DENTUSDT long 514.0 @ 0.009739 close @ 0.009853 enter @ 0.009641 || shrt 0.0 @ 0.0 close @ 0.0 enter @ 0.009827 || last 0.009724 liq 0.0 sl trig 0.0 ema 0.00979 bal 104.0 equity 104.0 v. 0.0204
2021-05-06T23:22:22  cancelled order DENTUSDT sell shrt 3874.0 0.011192
2021-05-06T23:22:59  DENTUSDT long 514.0 @ 0.009739 close @ 0.009853 enter @ 0.009641 || shrt 0.0 @ 0.0 close @ 0.0 enter @ 0.009827 || last 0.00969 liq 0.0 sl trig 0.0 ema 0.00979 bal 104.0 equity 104.0 v. 0.0204   Traceback (most recent call last):
  File "/opt/passivbot/.env/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 750, in transfer_data
    message = await self.read_message()
  File "/opt/passivbot/.env/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 819, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/opt/passivbot/.env/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 895, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/opt/passivbot/.env/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 971, in read_frame
    frame = await Frame.read(
  File "/opt/passivbot/.env/lib/python3.8/site-packages/websockets/legacy/framing.py", line 55, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "passivbot.py", line 621, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "passivbot.py", line 617, in main
    await start_bot(bot)
  File "passivbot.py", line 561, in start_bot
    await bot.start_websocket()
  File "/opt/passivbot/passivbot.py", line 536, in start_websocket
    async for msg in ws:
  File "/opt/passivbot/.env/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 356, in __aiter__
    yield await self.recv()
  File "/opt/passivbot/.env/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 421, in recv
    await self.ensure_open()
  File "/opt/passivbot/.env/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by eugjr** [comment]
Are you running it locally or on VPS?
I've stumbled within this same error about 3 times, all them running on VPS. Not sure if on VPS or Binance side.

**Comment by jeet2k123** [comment]
it's on a VM in Digital ocean running Ubuntu 20.4
